name: Test

on:
  push:
    branches:
      - main

jobs:
  ctest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up vcpkg
        run: |
          git clone --depth 1 -b 2025.08.27 https://github.com/microsoft/vcpkg.git vcpkg
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y ninja-build build-essential cmake
          echo "$(pwd)/vcpkg" >> $GITHUB_PATH
      - name: Build tests
        run: |
          ./vcpkg/bootstrap-vcpkg.sh
          cmake --preset CI_test
          cd ./build/debug && ninja
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      - name: Run tests
        run: ctest --test-dir ./build/debug/test
